apiVersion: v1
kind: Pod
metadata:
  name: <pod-name>
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: <container-name>
    image: <image-name>
    ports:
    - containerPort: 8080
    
    
   